---
title: "Practical Atheism (interview with Dr. Mohsen Javadi)"
format:
  revealjs: 
    theme: dark
#    footer: Religious Dewdrops
    self-contained: true
    smaller: true
    auto-stretch: true
    transition: slide
    background-transition: fade
categories:
  - atheism
  - interview
---

## Overarching Summary


. . .

A large portion of people, despite believing in God, Prophethood, and the Hereafter, are not bound to their religious beliefs when it comes to their actions and ethics.   

. . .

This is to the extent that practically there appears to be no difference between them and atheists. Their lives do not show any signs of God, or any fear of the Hereafter, rather it shows signs of individualism and heedlessness towards the Day of Judgement.  

. . .

This is a perilous state as it creates a harmful dichotomy in the lives of people (there is a practical life and another “theoretical one”. Remedying such a state is not uncomplicated.     

. . .


## Contents

- **Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies**   
- Practical atheism surfaces as one of four logically possible ways of living our lives  
- This way of living is particularly dangerous, introducing fundamental incoherence in lives   
- The ideal state of life and the self is one that is harmonious and coherent    
- Practical atheism has resulted from a complex mix of sociological and economic conditions   
- A complex problem often eludes a simple solution   
 

## Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies {.scrollable}  

- Practical atheism is when people believe in God, prophethood, and the hereafter but are not bound to their beliefs when it comes to their actions (i.e., they do not lead a life reflective of God consciousness).  
- Such people can be categorised as theoretical/theological believers but practically and ethically atheists or materialists.  
- This problem exists in other religions too, and is tackled with more rigour than amongst Muslims:  
   - For example, Cardinals of the Vatican are much more concerned with Christians drowning in the worship of the world and its material pleasures and their lack of attention to the real values of Christianity.  
- Nevertheless, this topic is quite an old one:  
   - For example, the notion of a scholar not acting according to knowledge   



## Contents

- Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies   
- **Practical atheism surfaces as one of four logically possible ways of living our lives**  
- This way of living is particularly dangerous, introducing fundamental incoherence in lives   
- The ideal state of life and the self is one that is harmonious and coherent    
- Practical atheism has resulted from a complex mix of sociological and economic conditions   
- A complex problem often eludes a simple solution 


## Practical atheism surfaces as one of four logically possible ways of living our lives V1

- There are logically four possible ways/scenarios of living:
   - Theoretically faithful + practical embodiment of faith in life  
   - Theoretically faithless + life is empty of faith too  
   - Theoretically faithless + life is a faithful one  
      - No harmony exists between practical and theoretical aspects of life
   - **Theoretically faithful + life is empty of faith**  
      - No harmony exists between practical and theoretical aspects of life

## Contents

- Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies   
- Practical atheism surfaces as one of four logically possible ways of living our lives  
- **This way of living is particularly dangerous, introducing fundamental incoherence in lives**   
- The ideal state of life and the self is one that is harmonious and coherent    
- Practical atheism has resulted from a complex mix of sociological and economic conditions   
- A complex problem often eludes a simple solution 


## This way of living is particularly dangerous, introducing fundamental incoherence in lives {.scrollable}

- People who succumb to practical atheism start defining and viewing relationships with other people through a materialist lens too.  
   - Their relationships become limited to only those that will produce material gains for the person.  
- Such people’s lives become incongruous, as what they perceive as being important in their minds (theoretical lives) are not practically important to them.   
- In reality, such people are materialists, and they have a greater chance of becoming a victim of their desires and ego, eventually **letting go of their faith (theoretical aspects of life) too, if it clashes with material benefits they seek to acquire**.   
   - This is because practical actions become habits, and eventually lifestyle.  
   - It is hard to change lifestyle, but easier to change theoretical beliefs.  
   - Faith can only remain if it is accompanied with actions.  
   - [30:10] “Then the fate of those who committed misdeeds was that they denied the signs of Allah and they used to deride them.”  
   - Such a person may end up like Yazid ibn Mu’awiyah, who eventually began saying there is no God and there was no prophet sent.  


## Contents

- Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies   
- Practical atheism surfaces as one of four logically possible ways of living our lives  
- This way of living is particularly dangerous, introducing fundamental incoherence in lives   
- **The ideal state of life and the self is one that is harmonious and coherent**    
- Practical atheism has resulted from a complex mix of sociological and economic conditions   
- A complex problem often eludes a simple solution 


## The ideal state of life and the self is one that is harmonious and coherent

- It is important to appreciate that all human activity is rooted in the self, which has different faculties and abilities, yet a single reality.  
- Depending on perspective we take to “view” the self, it comprises of **mind (contemplation), heart (emotions), and will (actions)**.  
- Given our will, there is an expectation of us to sometimes perform actions that may be difficult for us/contradicting our inclination.  
- The **Ideal state for the self** is a harmonious one:  
   - the mind, heart, and will must all be in congruence.  
   - If the mind uncovers divine realities/expectations, then will and heart must help in realising a life based on the uncovered realities.  


## Contents

- Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies   
- Practical atheism surfaces as one of four logically possible ways of living our lives  
- This way of living is particularly dangerous, introducing fundamental incoherence in lives   
- The ideal state of life and the self is one that is harmonious and coherent    
- **Practical atheism has resulted from a complex mix of sociological and economic conditions**   
- A complex problem often eludes a simple solution 


## Practical atheism has resulted from a complex mix of sociological and economic conditions {.scrollable}

- Religious discourse often focuses a lot on theoretical aspects while ignoring the human practical life, leading to a disjointed understanding of a virtuous life  
   - This is in spite of how major scholars believe “practical life” is more important  
   - It is possibly a residue from Greek philosophy’s, i.e., the postulation that man’s ability to contemplate is a chief virtue, more important than actions  
- Individualism and similar tendencies that slowly push humans to think they, in themselves, are paramount  
- Lack of human nobility in society, too, causes some issues which affect people deeply and create a breeding ground for practical atheism:  
   - Poverty  
   - Discrimination  
   - Humiliation (at the hands of other humans)  


## Contents

- Practical atheism is not a new phenomenon, although it is neglected these days in Muslim societies   
- Practical atheism surfaces as one of four logically possible ways of living our lives  
- This way of living is particularly dangerous, introducing fundamental incoherence in lives   
- The ideal state of life and the self is one that is harmonious and coherent    
- Practical atheism has resulted from a complex mix of sociological and economic conditions   
- **A complex problem often eludes a simple solution**   


## A complex problem often eludes a simple solution

. . .

Remedying practical atheism is hard because no single prescription - everyone’s life is different, in which different causes of practical atheism can be prevalent, and likewise different solutions can be adopted.  



## End


The original article can be found on [Iqra Online](https://iqraonline.net/some-thoughts-on-practical-atheism-dr-mohsen-javadi/)  

[Return home](www.religiousdewdrops.com)