---
title: "Isrā‘īliyāt’s Fiqhi Impact: Case Study on Women’s Ah̯kām"
format:
  revealjs: 
    theme: dark
#    footer: Religious Dewdrops
    self-contained: true
    smaller: true
    auto-stretch: true
    transition: slide
    background-transition: fade
---

## Overarching Summary


. . .

Torāhic and Biblical stories, such as the creation of Eve (a) from Adam (a), found their way into the early Muslim community, becoming a part of the Muslim psyche. 

. . .

The subconscious effect of such Isrā‘īliyāt has caused many Muslim scholars to interpret the underlying rationale of Qur’ānic ayāt and ahādith in ways that are in contravention of Qur’ānic and Prophetic (s) teachings/Sunnah, causing significant sociological challenges.

. . .

Example: Legal rulings related to women are often interpreted with such Isrā‘īliyāt, leading to sexist understandings that then negatively affect women in particular and society in general.

## Isrā‘īliyāt are pseudo-ahadith which originate from Judeo-Christian tradition

::: {.incremental}

- Isrā‘īliyāt can be:
  - In accord with Islamic principles
  - In contradiction with Islamic principles
  - Neither concurring, nor opposing
- Isrā‘īliyāt can be fictitious as well
:::

## Isrā‘īliyāt entered the Muslim community from early Jewish-to-Muslim converts

::: {.incremental}
- Isrā‘īliyāt often first found a place in the Sunni corpus, and subsequently entered the Shi’i corpus
- Several ex-Jews (e.g., Ka’b b. Māti’ H̯umayrī - d. 32AH, Wahb b. Munabbih - d. 110AH) were engrossed in inculcating such biblical mythology unto their new co-religionist brethren
:::

## Widespread dissemination of Isrā‘īliyāt amongst masses meant that Isrā‘īliyāt settled deeply within the Muslim psyche (v1) {.scrollable}

- Ahādīth were narrated that gave an apparent licence to relate traditions from Banu Isra’il
  - “Relate traditions from the Banu Isra’il; there is no harm” - Abu Hurayrah in Sunan Abu Dawud. 
  - Other examples are also available in Bukhari, At-Tirmizi, etc. 
- As age of tabi’in commenced, more Qur’anic scholars utilised Isrā‘īliyāt to clarify the ambiguous in the Holy Book, via eisegesis
  - Examples: Tabari; Abd Al Razzaq San’ani; 
  - As Tabari’s tafsīr was copied and popularised, Isrā‘īliyāt within it entered more Muslim communities
- And many more reasons also contributed towards Isrā‘īliyāt becoming firmly rooted:
  - Early ban on ahādīth documentation
  - Storytelling in the Arabian culture
  - Etc.

## An example from Isrā‘īliyāt: Eve (a) was created (literally) from Adam (a)

:::: {.columns}
::: {.column width="50%"}
**Torāhic verses** on the creation of Adam and Eve:  

  - “So the Lord God caused the man to fall into a deep sleep; and while he was sleeping, He took one of the man’s ribs and then closed up the place with flesh. Then the Lord God made a woman from the rib He had taken out of the man, and He brought her to the man.  
The man said, ‘This is now bone of my bones and flesh of my flesh; she shall be called woman, for she was taken out of man’” (Genesis, 2:21-3) 
:::
::: {.column width="50%"}
**Qur’ānic verse** on the creation of Adam and Eve:  

  - “...Fear your Lord who created you from a single soul, and from it created its match, and spread from the two, many men and women...” (Qur'ān, 4:1). 
  - “He is the One Who created you from a single soul, then from it made its spouse so he may find comfort in her...” (Qur'ān, 7:189) 
:::
::::  

## An example from Isrā‘īliyāt: Eve (a) was created (literally) from Adam (a) {.scrollable}


:::: {.columns}

::: {.column width="50%"}
Exegesis of the **Torāhic** verses by Jewish scholarship:  

  1. Eve (a) is from the essence and/or self of Adam (a)  
  2. Eve (a) was a part of Adam’s (a) body and was separated from him to come into existence
:::
::: {.column width="50%"}
Eisegesis of **Qur'ānic** verses by Muslim scholarship:  

  1. Eve (a) was created from Adam (a), specifically his rib.  
    - _This blatantly Torāhic view was found in Sunni ahādīth first, and then it found its way into Shi’i ahādīth_  
  2. Eve (a) was created from Adam (a), specifically from the residual clay  
    - _This only appears in Shi’i ahādīth, and still has its basis in the Torāhic genesis_  
  3. Eve (a) is from the same genus of Adam (a)  
    - _This is an unpopular view, and it also leads to the understanding that rulings/responsibilities of men and women differ by virtue of their roles, religious obligations, and physiques)_  
  - Isrā‘īliyāt were found to hold sway over a large number of Muslim exegetes  
:::
:::: 

## Isrā‘īliyāt are acting as a bias in interpretation of Qur'ānic verses

::: {.incremental} 
- Such Isrā‘īliyāt act as a bias in interpretation of the rationale behind women’s obligations and rights, causing significant sociological challenges

- Men and women’s rights and ahkām are similar, differing in minutiae due to unique biological, physiological, and psychological natures of each.  

- However, many stipulated that this difference is due to Eve (a) having been created from Adam (a). 
:::

## Examples of biased interpretations of the rationale behind women’s obligations and rights

::: {.panel-tabset}


### Hijab
Women and men are both obliged to observe the hijab, in different ways.  

Qur’ān rationale for the hijab: salvation, guardianship of faith, purity of heart, and an identification and defense for virtuous ladies from men whose hearts have a disease.  

Isrā‘īliyāt based rationale: Woman’s being from the “inside” (i.e., rib) of a man is the reason for women having to observe hijab 

### Inheritance

Men are assumed to have a higher share of inheritance, although there are times when, as per Islam, woman’s inheritance is equal or greater than man’s (e.g., 4:11 in Qur’an).  

Isrā‘īliyāt based rationale: Woman was created from left rib instead of right, hence they will have less share in inheritance 

### Right to divorce

Women have the right of approving their marriage, whereas men have the right to divorce.  

Isrā‘īliyāt based rationale: if man was made from woman, then woman would have had the right to divorce.  

### Education

Pseudo-ahādīth with strong basis in Isrā‘īliyāt are seen to propose a dislike for educating females and to prevent them from reciting Surah Yusuf.  

These are found in Shi’i and Sunni literature; they have problematic isnād/chains.    
They contradict Qurā’nic ahkām and Holy Prophet’s (s) Sunnah, which encourages education and recitation for all.  

Isrā‘īliyāt based justification: woman was created from man hence is inferior in regards to intelligence, and is thus incapable of understanding.

:::

## Isrā‘īliyāt have befouled Islamic culture, jurisprudence, and thought

. . . 

  
::: {.r-fit-text}  
The (preceding) comparison of these Torāhic accounts alongside Qurān’ic scripture highlights the shortcomings of many exegetes and transmitters of ahādīth...
:::
