project:
  type: website

website:
  title: "Religious Dewdrops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 2023-01-27-israiliyat-women-rights.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



